<a href="https://colab.research.google.com/github/Mochoye/ML_Bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is NumPy?**

NumPy is a Python library used for working with arrays.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


# **Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

**Arrays are very frequently used in data science, where speed and resources are very important.**

# **Why is NumPy Faster Than Lists?**

There are a few reasons why NumPy arrays are faster than Python lists.


*   **NumPy arrays are stored in contiguous memory**. This means that the elements of an array are stored next to each other in memory, which makes it very efficient to access them. Python lists, on the other hand, are not stored in contiguous memory, which can make accessing their elements slower.
*   **NumPy arrays are optimized for speed.** The NumPy library contains a number of functions that are specifically designed to be fast. These functions are often written in C or C++, which are languages that are known for their speed. Python lists, on the other hand, are not optimized for speed.



In [ ]:
!pip install numpy

In [1]:
import numpy as np

1. Create

In [2]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 8)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.78540121, 0.1988389 , 0.56155264, 0.51183225],
        [0.24868488, 0.07311919, 0.10642762, 0.13784841],
        [0.68324661, 0.35796666, 0.87423889, 0.34488861]],

       [[0.72325262, 0.01562663, 0.26097602, 0.84602266],
        [0.63543655, 0.48800152, 0.02158502, 0.60970829],
        [0.12934529, 0.02209961, 0.09508327, 0.27258182]]])

In [4]:
full

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

In [5]:
arr = np.array([[1,2,3,4],[1,2,3,4]])  #2,4

In [6]:
a=1

In [7]:
a = np.array([1,2,3,4])

In [8]:
type(arr)

numpy.ndarray

2. Read

In [21]:
data

array([[[0.78540121, 0.1988389 , 0.56155264, 0.51183225],
        [0.24868488, 0.07311919, 0.10642762, 0.13784841],
        [0.68324661, 0.35796666, 0.87423889, 0.34488861]],

       [[0.72325262, 0.01562663, 0.26097602, 0.84602266],
        [0.63543655, 0.48800152, 0.02158502, 0.60970829],
        [0.12934529, 0.02209961, 0.09508327, 0.27258182]]])

In [16]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [23]:
type(size)

int

In [20]:
types

dtype('float64')

In [26]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [29]:
singleval

0.7854012055616973

3. Update

In [34]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [39]:
list2

array([0.9389641 , 0.41903714, 0.3374905 , 0.7426078 , 0.83051828,
       0.11045563, 0.99484629, 0.57625946, 0.76820471, 0.92640054])

In [44]:
# Basic Math
add = np.add(list1, list2) #list1 + list 2
sub = np.subtract(list1, list2) # list1-list2
div = np.divide(list1, list2)#list1 / list2
mult = np.multiply(list1, list2)# list1 * list2
dot = np.dot(list1,list2)

In [45]:
dot

3.7418962583046778

In [46]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [53]:
maxs

0.9759076446020155

In [54]:
data

array([[[0.78540121, 0.1988389 , 0.56155264, 0.51183225],
        [0.24868488, 0.07311919, 0.10642762, 0.13784841],
        [0.68324661, 0.35796666, 0.87423889, 0.34488861]],

       [[0.72325262, 0.01562663, 0.26097602, 0.84602266],
        [0.63543655, 0.48800152, 0.02158502, 0.60970829],
        [0.12934529, 0.02209961, 0.09508327, 0.27258182]]])

In [55]:
data[0][0][0] = 700

In [56]:
data

array([[[7.00000000e+02, 1.98838901e-01, 5.61552643e-01, 5.11832254e-01],
        [2.48684882e-01, 7.31191884e-02, 1.06427620e-01, 1.37848407e-01],
        [6.83246613e-01, 3.57966664e-01, 8.74238890e-01, 3.44888606e-01]],

       [[7.23252620e-01, 1.56266332e-02, 2.60976019e-01, 8.46022663e-01],
        [6.35436555e-01, 4.88001524e-01, 2.15850216e-02, 6.09708292e-01],
        [1.29345286e-01, 2.20996107e-02, 9.50832684e-02, 2.72581823e-01]]])

In [57]:
data.sort()
data

array([[[1.98838901e-01, 5.11832254e-01, 5.61552643e-01, 7.00000000e+02],
        [7.31191884e-02, 1.06427620e-01, 1.37848407e-01, 2.48684882e-01],
        [3.44888606e-01, 3.57966664e-01, 6.83246613e-01, 8.74238890e-01]],

       [[1.56266332e-02, 2.60976019e-01, 7.23252620e-01, 8.46022663e-01],
        [2.15850216e-02, 4.88001524e-01, 6.09708292e-01, 6.35436555e-01],
        [2.20996107e-02, 9.50832684e-02, 1.29345286e-01, 2.72581823e-01]]])